[package]
description = "Parser for BER/DER encoding data"
license = "LGPL-2.1+"
keywords = ["BER","DER","ASN.1","ASN1","parser","nom"]
homepage = "https://github.com/rusticata/der-parser"
repository = "https://github.com/rusticata/der-parser.git"
name = "der-parser"
version = "0.1.1"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
nom = {version = "^2.0", features = ["verbose-errors"]}
log = "*"
env_logger = "*"
rusticata-macros = "*"
