[package]
description = "Parser for BER/DER encoding data"
license = "LGPL-2.1+"
keywords = ["BER","DER","ASN1","parser","nom"]
homepage = "https://github.com/rusticata/der-parser"
repository = "https://github.com/rusticata/der-parser.git"
name = "der-parser"
version = "0.3.5"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parsing"]

include = [
  "COPYING",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[dependencies]
nom = {version = "^2.0", features = ["verbose-errors"]}
rusticata-macros = "0.3.1"

[badges]
travis-ci = { repository = "rusticata/der-parser" }
